### ISSUE TITLE
Exception while running the WRN_28_8 pretrained model. 

### ISSUE THREAD

**Issue by hbake001** [titu1994/Wide-Residual-Networks#10]
Hi @titu1994 
I got the following excpetion while trying to run the `cifar10_wrn_28_8.py `file

```
Traceback (most recent call last):

  File "<ipython-input-4-a18c4043abdc>", line 1, in <module>
    runfile('C:/Users/engadmin/.spyder-py3/test_WRN28.py', wdir='C:/Users/engadmin/.spyder-py3')

  File "c:\users\engadmin\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "c:\users\engadmin\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/engadmin/.spyder-py3/test_WRN28.py", line 49, in <module>
    model.load_weights("WRN-28-8 Weights.h5")

  File "c:\users\engadmin\anaconda3\lib\site-packages\keras\engine\topology.py", line 2619, in load_weights
    load_weights_from_hdf5_group(f, self.layers)

  File "c:\users\engadmin\anaconda3\lib\site-packages\keras\engine\topology.py", line 3093, in load_weights_from_hdf5_group
    ' elements.')

ValueError: Layer #0 (named "conv2d_1" in the current model) was found to correspond to layer convolution2d_1 in the save file. However the new layer conv2d_1 expects 1 weights, but the saved weights have 2 elements.
```

**Comment by titu1994** [comment]
The weight files are for the older model setup. It won't work with this setup. 

I have not trained newer weight files yet since I don't have the resources to train these models currently.
